### ISSUE TITLE
No check if realloc returns null.

### ISSUE THREAD

**Issue by mbucc** [rxi/vec#1]
The OpenBSD man page has a great section on how to use realloc correctly.

http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man3/realloc.3

I guess an easy fix is to modify functions that allocate memory to return an int: 0 on success, ENOMEM if realloc fails.  It's even backwards compatible.  ;)

I really like the API otherwise.  Nice work.

**Comment by rxi** [comment]
Thanks for the input! The relevant functions now return `0` or, if an error occurs, return `-1` and leave the vector unchanged.

The exception to this is `vec_extend()` which is implemented as a `do {} while(0)` and so cannot return a value.
